### ISSUE TITLE
Installation instructions don't mention ECR

### ISSUE THREAD

**Issue by aaron-suarez** [sk4ddy/remediatetheflag#7]
In the pdf document, it shows that you need to build the docker images or push the prebuilt images to ECR. The `install.md` file makes no mention of docker.

![Screen Shot 2019-04-25 at 2 00 07 PM](https://user-images.githubusercontent.com/2008701/56761317-a5f0fa00-6762-11e9-80d6-49b2657bbb81.png)

Should Step 1 in `install.md` be "Push docker images to ECR"? Does the CloudFormation template pull the images from a public host by default?

**Comment by remediatetheflag** [comment]
The CloudFormation template pulls all the images for the RTF Platform Services from Docker Hub. The step when you push to ECR is to load Docker images for the RTF Exercises. Each exercise/group of exercises is a Docker image, please reference [configuration](https://github.com/sk4ddy/remediatetheflag/blob/master/docs/configure.md#Register%20Exercises%20on%20Regional%20Clusters) instructions. 
It's not required to pull the exercise image from Docker Hub and push it to ECR, but it's cheaper since data transferred between ECR and EC2 within a region is free of charge, so to lower costs keep the exercise images in the ECR repository
